### PR TITLE
Fix for Issue #28 - Does not work correctly with country groupings.

### PR DESCRIPTION
**Pull request by theresakhoo**

### CODE REVIEW

**Comment by grawk** [comment]
Hi @theresakhoo can you please have a look at the unit test failure?

**Comment by theresakhoo** [comment]
Hi @grawk.  The unit tests fail even without my change.  Even if I remove all tests, it still complains of a failure, but the details don't give much info.  Could be a tap thing, but I couldn't figure anything out from the documentation.

**Comment by grawk** [comment]
That's awesome. Thanks for finding that :)

I am going to close this PR since you can currently get the behavior you want by changing the second argument to `resolve` as an object (e.g. `{ country: 'CLAC_B', language: 'es', locale: 'es_CLAC_B' }`) instead of a string.

But if you have time, can you open up another PR to fix the unit test issue? If no time, I will file a bug and we can get to it when possible.

**Comment by theresakhoo** [comment]
@grawk Done.  See #30

**Pull request closed without merging**
