### PR TITLE
upgrade graceful-fs to 4.1.3

### PR DESCRIPTION
**Pull request by thefourtheye**
ref: https://github.com/krakenjs/file-resolver/issues/31

### CODE REVIEW

**Comment by grawk** [comment]
👍

**Comment by gabrielcsapo** [comment]
@grawk in the PR builder we aren't testing node 4, 5, or 6? is that intentional?

**Comment by grawk** [comment]
@gabrielcsapo no it's just that we have a lot of repos with out of date .travis.yml files. would be a good idea to modify that. either in this PR or a subsequent one.

**Comment by thefourtheye** [comment]
@grawk I can do that in this PR. Shall I include 4, 5 and 6?

**Comment by grawk** [comment]
@gabrielcsapo sounds good! probably remove v0.10 and iojs as well. thanks.

**Comment by gabrielcsapo** [comment]
@grawk @thefourtheye awesome :)

**Comment by thefourtheye** [comment]
@grawk Done! PR is updated now.

**Comment by gabrielcsapo** [comment]
@grawk LGTM 👍

**Comment by thefourtheye** [comment]
Bump

**Comment by wikiziner** [comment]
+1

**Comment by gabrielcsapo** [comment]
Thank you @aredridel!

**Comment by thefourtheye** [comment]
Thanks :-) Can someone take a look at https://github.com/krakenjs/grunt-localizr/pull/24 as well?

**Pull request merged**
